addpath('/home/eld615/DAD/toolboxes/lsge-matlab')
addpath('/home/eld615/DAD/data')     
addpath('/home/eld615/DAD/toolboxes/drtoolbox')
addpath('/home/eld615/DAD/toolboxes/drtoolbox/techniques')
addpath('/home/eld615/DAD/code/scripts_forpaper')
addpath('/home/eld615/DAD')
addpath('/home/eld615/DAD/code')
