addpath('/home/eld615/DAD/lsge-matlab') 
addpath('/home/eld615/DAD/data')     
addpath('/home/eld615/DAD/drtoolbox')
addpath('/home/eld615/DAD/drtoolbox/techniques')
addpath('/home/eld615/DAD/code/scripts_forpaper')
addpath('/home/eld615/DAD')
addpath('/home/eld615/DAD/code')
